version: "3.6"

services:
  db:
    image: postgres:10.3
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/10.3/data

volumes:
  pgdata:
