name: Elixir CI
env:
  MIX_ENV: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:10
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
        ports: ['6432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.2 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]

    - name: Get deps cache
      uses: actions/cache@v1
      with:
        path: deps/
        key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-deps-

    - name: Get build cache
      uses: actions/cache@v1
      with:
        path: _build/test/
        key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-build-

    - name: Install Dependencies
      run: |
        mix deps.get
        mix compile

    - name: Run Tests
      run: mix coveralls.json

    - name: Push Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)

    - name: Run Credo
      run: mix credo suggest --strict --format=flycheck
